// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 9.0
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_fly(c,a,b){var e=jQuery;var f=e(this);var h={position:"absolute",left:0,top:0,width:"100%",height:"100%",transform:"translate3d(0,0,0)"};var d=b.find(".ws_list");var g=e("<div>").addClass("ws_effect ws_fly").css(h).css({overflow:"visible"}).appendTo(b);this.go=function(p,m,l){if(l==undefined){l=!!c.revers}else{l=!l}var k=-(c.distance||g.width()/4),n=Math.min(-k,Math.max(0,e(window).width()-g.offset().left-g.width())),i=(l?n:k),q=(l?k:n);var j=e(a.get(m));j={width:j.width(),height:j.height()};var r=e("<div>").css(h).css({"z-index":1,overflow:"hidden"}).html(e(a.get(m)).clone().css(j)).appendTo(g);var o=e("<div>").css(h).css({"z-index":3,overflow:"hidden"}).html(e(a.get(p)).clone().css(j)).appendTo(g).show();wowAnimate(o,{opacity:0},{opacity:1},c.duration);wowAnimate(o,{left:i},{left:0},2*c.duration/3);d.hide();wowAnimate(r,{left:0,opacity:1},{left:q,opacity:0},2*c.duration/3,c.duration/3,function(){r.remove();f.trigger("effectEnd");o.remove()})}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 9.0
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container0").wowSlider({effect:"fly",prev:"",next:"",duration:20*100,delay:20*100,width:1366,height:768,autoPlay:true,autoPlayVideo:false,playPause:true,stopOnHover:false,loop:false,bullets:1,caption:true,captionEffect:"parallax",controls:true,controlsThumb:["data0/images/318724498_208627931645999_6526740235999673150_n.jpg", "data0/images/319035741_209058571602935_1762384661587227135_n.jpg", "data0/images/320204205_540646731297523_3313640484749189840_n.jpg", "data0/images/321504246_681441566785994_3428222561282726183_n.jpg", "data0/images/325864106_1328603164349484_5302459083148243483_n.jpg", "data0/images/350111023_1267341957221563_931062848553406833_n.jpg", "data0/images/363388039_298434572695311_6298884055877534730_n.jpg", "data0/images/364224404_300551509150284_3517523131442457316_n.jpg", "data0/images/365740422_298269519378483_4781081375571676090_n.jpg", "data0/images/368261463_305015158703919_1980880672230878381_n.jpg", "data0/images/369473089_306468851891883_6368630967644262697_n.jpg", "data0/images/369514917_306468855225216_7212968139389899229_n.jpg", "data0/images/369525737_306468848558550_53591354735990100_n.jpg", "data0/images/370781685_309388658266569_7671113956840703351_n.jpg", "data0/images/370928846_309388631599905_5520089409767008778_n.jpg", "data0/images/376780962_316563984215703_2393017007258477972_n.jpg"],responsive:2,fullScreen:false,gestures:2,onBeforeStep:0,images:0});